version: '3'

services:
  goapp:
    build: .
    volumes:
      - .:/go/app
    platform: linux/amd64
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mysql:
    image: mysql:5.7
    container_name: mysql2
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hauling
      MYSQL_PASSWORD: root
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - ./mysql:/var/lib/mysql
